/*
 * Copyright 2026 Vadim Aleksandrovich Zaletaev
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 * SPDX-License-Identifier: MPL-2.0
 */

package ru.pathcreator.vadim.quantum.chemistry.domain.diagnostic;

public enum ChemistryDiagnosticCode {

  MOLECULE_HAS_NO_BONDS,
  MOLECULE_HAS_NO_GEOMETRY,
  MOLECULE_CHARGE_DOES_NOT_MATCH_ATOMS,
  MOLECULE_RADICAL_SPIN_NEEDS_REVIEW,
  MOLECULE_RADICAL_SPIN_MULTIPLICITY_MISMATCH,
  MOLECULE_SPIN_MULTIPLICITY_INCOMPATIBLE_WITH_ELECTRONS,
  MOLECULE_GRAPH_IS_DISCONNECTED,
  MOLECULE_STEREOCHEMISTRY_NEEDS_GEOMETRY,
  MOLECULE_CONFORMATION_NEEDS_GEOMETRY,
  MOLECULE_OPTICAL_ROTATION_WITHOUT_STEREOCHEMISTRY,
  MOLECULE_UNKNOWN_BOND_ORDER,
  MOLECULE_VALENCE_EXCEEDS_PROFILE,
  REACTION_ATOMS_NOT_BALANCED,
  REACTION_CHARGE_NOT_BALANCED,
  REACTION_MECHANISM_HAS_NO_ENERGY_PROFILE,
  REACTION_MECHANISM_STEP_HAS_NO_TRANSITION_STATE,
  REACTION_MECHANISM_STEP_HAS_NO_FORWARD_BARRIER,
  REACTION_MECHANISM_STEP_HAS_NO_REVERSE_BARRIER,
  REACTION_MECHANISM_STEP_HAS_NO_REACTION_ENERGY,
  REACTION_MECHANISM_ENERGY_PROFILE_TRANSITION_STATE_MISMATCH,
  THERMODYNAMIC_PROFILE_HAS_NO_DIRECT_GIBBS_DATA,
  THERMODYNAMIC_PROFILE_HAS_NO_ENTROPY_DATA,
  THERMODYNAMIC_PROFILE_HAS_NO_ZERO_POINT_ENERGY_DATA,
  KINETIC_PROFILE_HAS_NO_MEASUREMENTS,
  KINETIC_PROFILE_MEASUREMENT_RESIDUAL_DETECTED,
  MOLECULAR_PROPERTY_SET_HAS_IMAGINARY_FREQUENCIES,
  MOLECULAR_PROPERTY_SET_HAS_NO_DIPOLE_MOMENT,
  MOLECULAR_PROPERTY_SET_HAS_NO_PARTIAL_CHARGE_MODEL,
  MOLECULAR_PROPERTY_SET_HAS_NO_VIBRATIONAL_MODES,
  SPECTROSCOPY_SET_HAS_NO_ELECTRONIC_TRANSITIONS,
  SPECTROSCOPY_SET_HAS_NO_OPTICALLY_ALLOWED_TRANSITIONS,
  SPECTROSCOPY_SET_HAS_NO_NMR_OBSERVABLES,
  REACTION_TASK_REQUIRES_REACTION_SUBJECT,
  MOLECULE_TASK_REQUIRES_MOLECULE_SUBJECT,
  TASK_HAS_NO_ACTIVE_SPACE,
  ACTIVE_SPACE_HAS_TOO_MANY_ELECTRONS,
  METHOD_SPIN_TREATMENT_INCOMPATIBLE_WITH_SUBJECT,
  QUANTUM_ROUTE_REQUIRES_ACTIVE_SPACE,
  ELECTRONIC_PROBLEM_HAS_NO_ELECTRONIC_TERMS,
  ELECTRONIC_HAMILTONIAN_HAS_ZERO_INTEGRAL_TERMS,
  ELECTRONIC_HAMILTONIAN_HAS_NO_ORBITAL_COUPLINGS,
  ELECTRONIC_HAMILTONIAN_IS_DENSE_TENSOR,
  ELECTRONIC_PROBLEM_HAS_NO_ORBITAL_BASIS,
  ELECTRONIC_PROBLEM_HAS_FRACTIONAL_ORBITAL_OCCUPATION,
  ELECTRONIC_PROBLEM_TASK_REQUIRES_MOLECULE_SCOPE,
  ELECTRONIC_PROBLEM_ORBITAL_OCCUPATION_MISMATCH,
  ELECTRONIC_PROBLEM_ACTIVE_SPACE_EXCEEDS_MOLECULE_ELECTRONS,
  CLASSICAL_AND_QUANTUM_COMPARISON_REQUIRES_SHARED_TASK,
  MICROSTATE_SET_HAS_NO_ENVIRONMENT,
  ACID_BASE_MODEL_HAS_NO_PH_CONTEXT,
  REDOX_MODEL_HAS_NO_FORMAL_POTENTIALS;
}